spring.application.name=pmoc

#spring.datasource.url=jdbc:postgresql://localhost:5432/pmocdb
#spring.datasource.username=postgres
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

api.security.token.secret="123"

#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.enabled=false