spring.application.name=pmoc

spring.datasource.url=jdbc:postgresql://localhost:5432/pmocdb
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false